#!/usr/bin/env python3
"""
Rebuild the insider_trades table from NSE PIT (Prohibition of Insider Trading)
disclosures — the canonical, unlimited-row source for promoter/director trades.

NSE PIT covers: promoter, promoter group, director, KMP (key managerial personnel),
and other connected persons. It does NOT cover bulk/block deals — those are separate
(use fetch_bulkdeals.py for those).

Usage:
    python3 fetch_insider_history.py                   # default: last 2 years
    python3 fetch_insider_history.py --from 2024-01    # from Jan 2024 to today
    python3 fetch_insider_history.py --from 2024-01 --to 2024-06  # specific range
    python3 fetch_insider_history.py --month 2024-03   # single month

If a month fetch fails, the script prints a fallback instruction:
    "Drop the TickerTape CSV for that month in insider_trades/ and run:
     python3 process_insider_trades.py --force"

NSE PIT API: https://www.nseindia.com/api/corporates-pit
  - index=equities
  - from_date / to_date: DD-Mon-YYYY (e.g. 01-Jan-2024)
  - Returns JSON: {"acqNameList": [...], "data": [...]}
  - Session cookie required — loaded from cookies.txt (generated by curl)
"""
import argparse
import http.cookiejar
import sys
import time
import urllib.request
import json
from datetime import date, datetime, timedelta
from pathlib import Path

# ────────────────────────────────────────────────────────────────────────────
# Category → tier mapping (mirrors process_insider_trades.py logic)
# ────────────────────────────────────────────────────────────────────────────

_TIER_MAP = {
    "promoter":               "promoter",
    "promoter group":         "promoter",
    "promoter and promoter group": "promoter",
    "director":               "director",
    "key managerial personnel": "director",
    "kmp":                    "director",
    "designated person":      "connected",
    "connected person":       "connected",
    "relative of promoter":   "connected",
    "relative":               "connected",
    "employee":               "connected",
}

def _category_to_tier(raw_category: str) -> str:
    if not raw_category:
        return "connected"
    low = raw_category.lower().strip()
    for key, tier in _TIER_MAP.items():
        if key in low:
            return tier
    return "connected"


# ────────────────────────────────────────────────────────────────────────────
# Date helpers
# ────────────────────────────────────────────────────────────────────────────

def _parse_trade_date(raw: str) -> str | None:
    """
    NSE sends dates in various formats:
      "29-Apr-2026", "02-May-2026 16:46", "01-Jan-2024"
    Returns ISO date string "YYYY-MM-DD", or None if unparseable.
    """
    if not raw:
        return None
    raw = raw.strip().split()[0]  # strip time component if present
    for fmt in ("%d-%b-%Y", "%d-%m-%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(raw, fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def _nse_date(d: date) -> str:
    """date → 'DD-Mon-YYYY' format expected by NSE API."""
    return d.strftime("%d-%b-%Y")


def _months_in_range(from_ym: str, to_ym: str) -> list[tuple[date, date]]:
    """
    Returns list of (month_start, month_end) date pairs for each calendar month
    between from_ym and to_ym inclusive. Format: 'YYYY-MM'.
    """
    y0, m0 = int(from_ym[:4]), int(from_ym[5:7])
    y1, m1 = int(to_ym[:4]), int(to_ym[5:7])
    result = []
    y, m = y0, m0
    while (y, m) <= (y1, m1):
        start = date(y, m, 1)
        # Last day of month: first day of next month - 1 day
        if m == 12:
            end = date(y + 1, 1, 1) - timedelta(days=1)
        else:
            end = date(y, m + 1, 1) - timedelta(days=1)
        # Don't go past today
        end = min(end, date.today())
        result.append((start, end))
        m += 1
        if m > 12:
            m = 1
            y += 1
    return result


# ────────────────────────────────────────────────────────────────────────────
# NSE session (cookie-based)
# ────────────────────────────────────────────────────────────────────────────

COOKIES_FILE = Path("cookies.txt")

# Public headers that pass NSE's bot detection
_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.nseindia.com/companies-listing/corporate-filings-pit",
    "X-Requested-With": "XMLHttpRequest",
}


def _build_opener() -> urllib.request.OpenerDirector:
    """Build a URL opener with cookies loaded from cookies.txt."""
    jar = http.cookiejar.MozillaCookieJar()
    if COOKIES_FILE.exists():
        try:
            jar.load(str(COOKIES_FILE), ignore_discard=True, ignore_expires=True)
        except Exception as e:
            print(f"  Warning: could not load cookies.txt — {e}")
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))
    opener.addheaders = list(_HEADERS.items())
    return opener


def _warmup(opener: urllib.request.OpenerDirector) -> bool:
    """
    Hit the NSE homepage to establish a fresh session if the stored cookie
    has expired. Returns True on success, False if the warmup itself failed.
    """
    try:
        req = urllib.request.Request(
            "https://www.nseindia.com",
            headers=_HEADERS,
        )
        with opener.open(req, timeout=15) as resp:
            _ = resp.read(1024)  # consume headers only
        return True
    except Exception as e:
        print(f"  NSE warmup failed: {e}")
        return False


# ────────────────────────────────────────────────────────────────────────────
# Fetch one month
# ────────────────────────────────────────────────────────────────────────────

_PIT_URL = (
    "https://www.nseindia.com/api/corporates-pit"
    "?index=equities&from_date={from_date}&to_date={to_date}"
)

_MAX_RETRIES = 3
_RETRY_DELAY = 8   # seconds between retries (NSE rate-limits aggressively)
_TIMEOUT     = 30  # per-request timeout in seconds


def _fetch_month(
    opener: urllib.request.OpenerDirector,
    start: date,
    end: date,
) -> list[dict] | None:
    """
    Fetch NSE PIT records for one calendar month.
    Returns list of raw dicts from the 'data' array, or None on persistent failure.
    Retries up to _MAX_RETRIES times with _RETRY_DELAY seconds between attempts.
    """
    url = _PIT_URL.format(
        from_date=_nse_date(start),
        to_date=_nse_date(end),
    )

    for attempt in range(1, _MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers=_HEADERS)
            with opener.open(req, timeout=_TIMEOUT) as resp:
                raw = resp.read()
            payload = json.loads(raw)
            return payload.get("data", [])
        except Exception as e:
            if attempt < _MAX_RETRIES:
                print(f"    attempt {attempt} failed ({e}) — retrying in {_RETRY_DELAY}s...")
                time.sleep(_RETRY_DELAY)
            else:
                print(f"    all {_MAX_RETRIES} attempts failed: {e}")
                return None

    return None


# ────────────────────────────────────────────────────────────────────────────
# Field mapping (NSE PIT → insider_trades row dict)
# ────────────────────────────────────────────────────────────────────────────

def _map_row(rec: dict, source_label: str) -> dict | None:
    """
    Map one NSE PIT JSON record to the dict shape expected by
    market_db.insert_insider_trade(). Returns None to skip the record.

    Key NSE fields:
      symbol              → ticker
      acqName             → party_name
      personCategory      → category + tier
      tdpTransactionType  → trade_type ("Buy" → "buy", "Sell" → "sell")
      secAcq              → quantity (number of shares)
      secVal              → total transaction value in rupees → /1e7 for Crores
      acqfromDt           → trade date (various formats, see _parse_trade_date)
      befAcqSharesPer     → holding % before trade
      afterAcqSharesPer   → holding % after trade
    """
    ticker = (rec.get("symbol") or "").strip().upper()
    if not ticker:
        return None

    raw_type = (rec.get("tdpTransactionType") or "").strip().lower()
    if "buy" in raw_type:
        trade_type = "buy"
    elif "sell" in raw_type:
        trade_type = "sell"
    else:
        return None  # skip pledge/transmission/acquisition types

    trade_date = _parse_trade_date(rec.get("acqfromDt") or "")
    if not trade_date:
        return None

    category   = (rec.get("personCategory") or "").strip()
    tier       = _category_to_tier(category)
    party_name = (rec.get("acqName") or "").strip()
    if not party_name:
        return None

    try:
        quantity = int(float(rec.get("secAcq") or 0))
    except (ValueError, TypeError):
        quantity = None

    try:
        sec_val  = float(rec.get("secVal") or 0)
        value_cr = round(sec_val / 1e7, 4) if sec_val else None
    except (ValueError, TypeError):
        value_cr = None

    # Derived avg_price: total value (₹) / quantity
    avg_price = None
    if quantity and quantity > 0 and value_cr:
        avg_price = round((value_cr * 1e7) / quantity, 2)

    # Change in promoter stake
    try:
        before = float(rec.get("befAcqSharesPer") or 0)
        after  = float(rec.get("afterAcqSharesPer") or 0)
        holdings_change_pct = round(after - before, 4) if (before or after) else None
    except (ValueError, TypeError):
        holdings_change_pct = None

    return {
        "date":                trade_date,
        "ticker":              ticker,
        "party_name":          party_name,
        "category":            category,
        "tier":                tier,
        "trade_type":          trade_type,
        "quantity":            quantity,
        "value_cr":            value_cr,
        "avg_price":           avg_price,
        "holdings_change_pct": holdings_change_pct,
        "source_file":         source_label,
    }


# ────────────────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────────────────

def _cookies_stale(max_age_days: int = 7) -> bool:
    """True if cookies.txt is missing or last modified more than max_age_days ago."""
    p = COOKIES_FILE
    if not p.exists():
        return True
    age_days = (datetime.now() - datetime.fromtimestamp(p.stat().st_mtime)).days
    return age_days >= max_age_days


def _auto_refresh_cookies():
    """
    Silently refresh NSE session cookies via Playwright if they are stale.
    Prints a one-line status. Never raises — if Playwright is unavailable or
    refresh fails, the existing cookies (however stale) are used as fallback.
    """
    try:
        from browser_utils import get_nse_cookies
        print("Cookies stale — refreshing via Playwright (takes ~10s)...")
        result = get_nse_cookies(headless=True)
        if result and "bm_sv" in result:
            print("  Cookie refresh OK.")
        else:
            print("  Cookie refresh returned no bm_sv — proceeding with existing cookies.")
    except ImportError:
        print(
            "  playwright not installed — proceeding with existing cookies.\n"
            "  To enable auto-refresh: pip install playwright && "
            "python3 -m playwright install chromium"
        )
    except Exception as e:
        print(f"  Cookie refresh failed ({e}) — proceeding with existing cookies.")


def run(from_ym: str, to_ym: str):
    """Fetch all months in [from_ym, to_ym] and insert into market_db."""
    sys.path.insert(0, str(Path(__file__).parent))
    import market_db as mdb

    conn = mdb.get_conn()
    months = _months_in_range(from_ym, to_ym)

    print(f"\nNSE PIT history rebuild: {from_ym} → {to_ym} ({len(months)} months)\n")

    # Auto-refresh cookies before the first API call if they are stale
    if _cookies_stale():
        _auto_refresh_cookies()

    opener = _build_opener()

    # Warm up session — hit the NSE homepage so the session is live
    print("Warming up NSE session...")
    if not _warmup(opener):
        print("  Warning: warmup failed — proceeding anyway (cookies may still be valid)")
    time.sleep(1)

    total_fetched  = 0
    total_inserted = 0
    failed_months  = []

    for start, end in months:
        label = start.strftime("%Y-%m")
        print(f"  {label}: fetching {_nse_date(start)} → {_nse_date(end)} ...", end=" ", flush=True)

        records = _fetch_month(opener, start, end)
        if records is None:
            print(f"FAILED")
            failed_months.append(label)
            # Polite pause before continuing to the next month
            time.sleep(5)
            continue

        month_rows     = 0
        month_inserted = 0
        source_label   = f"NSE-PIT-{label}"

        for rec in records:
            row = _map_row(rec, source_label)
            if row is None:
                continue
            before = conn.execute("SELECT changes()").fetchone()[0]
            mdb.insert_insider_trade(conn, row)
            month_rows += 1

        conn.commit()

        # Count actual inserts by querying source_file rows added this batch
        inserted = conn.execute(
            "SELECT COUNT(*) FROM insider_trades WHERE source_file = ?",
            (source_label,),
        ).fetchone()[0]

        print(f"{len(records)} records → {inserted} in DB (source={source_label})")
        total_fetched  += len(records)
        total_inserted += inserted

        # Polite pause between months — NSE rate-limits quickly
        time.sleep(2)

    conn.close()

    # ── Summary ──────────────────────────────────────────────────────────────
    print(f"\n{'─'*60}")
    print(f"Fetched : {total_fetched:,} NSE PIT records")
    print(f"In DB   : {total_inserted:,} rows (deduplicated by UNIQUE constraint)")
    print(f"Months  : {len(months) - len(failed_months)}/{len(months)} succeeded")

    if failed_months:
        print(f"\n⚠️  {len(failed_months)} month(s) failed to fetch:")
        for ym in failed_months:
            print(f"   {ym}")
        print(
            "\nFallback for failed months:"
            "\n  1. Download the TickerTape CSV for that month from"
            "\n     https://www.tickertape.in/market-pulse/insider-trades"
            "\n  2. Drop the CSV in insider_trades/"
            "\n  3. python3 process_insider_trades.py --force"
        )
    print()


def main():
    today = date.today()
    two_years_ago = date(today.year - 2, today.month, 1)

    parser = argparse.ArgumentParser(
        description="Rebuild insider_trades table from NSE PIT API (2-year history).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--from", dest="from_ym", metavar="YYYY-MM",
        default=two_years_ago.strftime("%Y-%m"),
        help=f"Start month (default: {two_years_ago.strftime('%Y-%m')})",
    )
    parser.add_argument(
        "--to", dest="to_ym", metavar="YYYY-MM",
        default=today.strftime("%Y-%m"),
        help=f"End month (default: {today.strftime('%Y-%m')})",
    )
    parser.add_argument(
        "--month", metavar="YYYY-MM",
        help="Fetch a single month (overrides --from/--to)",
    )
    args = parser.parse_args()

    if args.month:
        run(args.month, args.month)
    else:
        run(args.from_ym, args.to_ym)


if __name__ == "__main__":
    main()
