#!/usr/bin/env python3
"""
Refresh NSE session cookies (bm_sv) via headless Chromium.

The NSE PIT API requires an Akamai bot-management cookie generated by JavaScript
running in a real browser. This script launches headless Chromium, visits the NSE
PIT page, lets the challenge complete, and saves fresh cookies to cookies.txt.

Usage:
    python3 refresh_nse_cookies.py          # refresh + write cookies.txt
    python3 refresh_nse_cookies.py --check  # print current age, exit 0 if fresh

Called automatically by fetch_insider_history.py when cookies are stale (>7 days).
"""
import sys
from datetime import datetime
from pathlib import Path

COOKIES_FILE = Path("cookies.txt")
MAX_AGE_DAYS = 7


def _cookie_age_days() -> float | None:
    """Return age of cookies.txt in days, or None if it doesn't exist."""
    if not COOKIES_FILE.exists():
        return None
    mtime = datetime.fromtimestamp(COOKIES_FILE.stat().st_mtime)
    return (datetime.now() - mtime).total_seconds() / 86400


def check_mode():
    age = _cookie_age_days()
    if age is None:
        print("cookies.txt: missing")
        sys.exit(1)
    elif age >= MAX_AGE_DAYS:
        print(f"cookies.txt: STALE ({age:.1f} days old, max {MAX_AGE_DAYS})")
        sys.exit(1)
    else:
        print(f"cookies.txt: fresh ({age:.1f} days old)")
        sys.exit(0)


def refresh_mode():
    age = _cookie_age_days()
    if age is not None:
        print(f"Current cookies.txt age: {age:.1f} days — refreshing...")
    else:
        print("cookies.txt missing — fetching fresh session...")

    from browser_utils import get_nse_cookies
    result = get_nse_cookies(headless=True)

    if result:
        new_age = _cookie_age_days()
        bm_sv = "bm_sv" in result
        print(
            f"Done. {len(result)} cookies saved to cookies.txt "
            f"({'bm_sv present ✓' if bm_sv else 'WARNING: bm_sv missing'})"
        )
        return True
    else:
        print("FAILED — see logs above. Try running with headless=False for debugging:")
        print("  python3 browser_utils.py cookies")
        return False


if __name__ == "__main__":
    if "--check" in sys.argv:
        check_mode()
    else:
        ok = refresh_mode()
        sys.exit(0 if ok else 1)
